name: tests

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

jobs:
  tests:
    name: Tests (${{ matrix.env-name }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        env-name: ['py36', 'py37', 'py38']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: false
          activate-environment: test_env_${{ matrix.env-name }}
          environment-file: ci/requirements/${{ matrix.env-name }}.yml
          auto-activate-base: false
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Install xarray-simlab
        shell: bash -l {0}
        run: |
          pip install --no-deps -e .
          python -OO -c "import xsimlab"
      - name: Run tests
        shell: bash -l {0}
        run: pytest xsimlab --verbose --color=yes
